package com.mycompany.minhadispensa;

import javax.persistence.EntityManager;

public class Inicio extends javax.swing.JFrame {

    private Usuario usuario;
    private EntityManager em;

    public Inicio(Usuario usuario, EntityManager em) {
        this.usuario = usuario;
        this.em = em;
        initComponents();
        jlblNomeDoUsuarioLogado.setText(usuario.getNome()); // Define o nome do usuário no JLabel
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblMensagenBoasVindas = new javax.swing.JLabel();
        jlblNomeDoUsuarioLogado = new javax.swing.JLabel();
        jbtnDispensa = new javax.swing.JButton();
        jbtnReceitas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblMensagenBoasVindas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlblMensagenBoasVindas.setText("Seja Bem Vindo");

        jlblNomeDoUsuarioLogado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jbtnDispensa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnDispensa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/minhadispensa/Imagens/Cesta_de_compras.jpg"))); // NOI18N
        jbtnDispensa.setText("Dispensa");
        jbtnDispensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDispensaActionPerformed(evt);
            }
        });

        jbtnReceitas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnReceitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/minhadispensa/Imagens/receitas.jpg"))); // NOI18N
        jbtnReceitas.setText("Receitas    ");
        jbtnReceitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReceitasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblMensagenBoasVindas)
                        .addGap(26, 26, 26)
                        .addComponent(jlblNomeDoUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtnDispensa, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnReceitas, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblMensagenBoasVindas)
                    .addComponent(jlblNomeDoUsuarioLogado))
                .addGap(48, 48, 48)
                .addComponent(jbtnDispensa, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jbtnReceitas, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDispensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDispensaActionPerformed
        Dispensa dispensa = new Dispensa(usuario, em);
        dispensa.setVisible(true);
        dispensa.setLocationRelativeTo(null);  // Centraliza a janela
    }//GEN-LAST:event_jbtnDispensaActionPerformed

    private void jbtnReceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReceitasActionPerformed
        Receitas receitas = new Receitas(usuario, em);
        receitas.setVisible(true);
        receitas.setLocationRelativeTo(null);  // Centraliza a janela
    }//GEN-LAST:event_jbtnReceitasActionPerformed

    //este trecho foi removido

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnDispensa;
    private javax.swing.JButton jbtnReceitas;
    private javax.swing.JLabel jlblMensagenBoasVindas;
    private javax.swing.JLabel jlblNomeDoUsuarioLogado;
    // End of variables declaration//GEN-END:variables
}
